# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 16:49
from __future__ import unicode_literals

import cms.models.pluginmodel
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_css_background', '0002_filercssbackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssbackground',
            name='attachment',
            field=models.CharField(blank=True, choices=[('', 'Inherit'), ('fixed', 'Fixed'), ('scroll', 'Scrolling')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cssbackground',
            name='bg_position',
            field=models.CharField(blank=True, default='', help_text='Blank will inherit page CSS styling.', max_length=24, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='cssbackground',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Blank will inherit page CSS styling.', max_length=32),
        ),
        migrations.AlterField(
            model_name='cssbackground',
            name='image',
            field=models.ImageField(blank=True, help_text='Blank will inherit page CSS styling.', null=True, upload_to=cms.models.pluginmodel.get_plugin_media_path),
        ),
        migrations.AlterField(
            model_name='cssbackground',
            name='repeat',
            field=models.CharField(blank=True, choices=[('', 'Inherit'), ('repeat', 'Tile in both directions'), ('repeat-x', 'Tile horizontally'), ('repeat-y', 'Tile vertically'), ('no-repeat', 'No tiling')], default='', max_length=16, verbose_name='Tiling'),
        ),
        migrations.AlterField(
            model_name='filercssbackground',
            name='attachment',
            field=models.CharField(blank=True, choices=[('', 'Inherit'), ('fixed', 'Fixed'), ('scroll', 'Scrolling')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='filercssbackground',
            name='bg_position',
            field=models.CharField(blank=True, default='', help_text='Blank will inherit page CSS styling.', max_length=24, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='filercssbackground',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Blank will inherit page CSS styling.', max_length=32),
        ),
        migrations.AlterField(
            model_name='filercssbackground',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Blank will inherit page CSS styling.', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='filercssbackground',
            name='repeat',
            field=models.CharField(blank=True, choices=[('', 'Inherit'), ('repeat', 'Tile in both directions'), ('repeat-x', 'Tile horizontally'), ('repeat-y', 'Tile vertically'), ('no-repeat', 'No tiling')], default='', max_length=16, verbose_name='Tiling'),
        ),
    ]
