# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cmsplugin_css_background', '0005_update_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='filercssbackground',
            name='thumbnailoption',
            field=models.ForeignKey(blank=True, help_text='Use the thumbnail image size defined by this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.ThumbnailOption', verbose_name='Thumbnail Option'),
        ),
        migrations.AlterField(
            model_name='cssbackground',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_css_background_cssbackground', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='filercssbackground',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_css_background_filercssbackground', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
